config/routes.rb
Rails.application.routes.draw do

  root 'articles#index'

  resources :articles

end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    respond_to do |format|
      format.html do
        @articles = Article.all
        @article = Article.new
        render :index
      end
      format.json { render json: Article.all }
    end
  end

  def create
    article = Article.new article_params
    if article.save
      render partial: 'article', locals: { article: article }
    else
      render status: :bad_request
    end
  end

  def destroy
    article = Article.find_by_id params[:id]
    if article
      article.destroy
      render nothing: true
    else
      render plain: 'Not found', status: :not_found
    end
  end

private

  def article_params
    params.require(:article).permit(:title, :text)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<tr>
  <td><%= article.title %></td><td><%= article.text %></td>
  <td><%= button_to 'Delete article', article_path(article.id), method: :delete, remote: true, class: 'delete-button' %></td>
</tr>

app/views/articles/index.html.erb
<h1>Articles</h1>
<%= form_for :article, url: articles_path, method: :post, remote: true do |f| %>
  <%= f.text_field :title %>
  <%= f.text_field :text %>
  <%= f.submit 'Add article', class: 'add-button' %>
<% end %>
<table class="table">
  <tr><th>Title</th><th>Text</th><th>Action</th></tr>
  <%= render partial: 'article', collection: @articles %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Simple</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>